### PR TITLE
[naoqi_apps] add node and launch for ALSoundLocalization

### PR DESCRIPTION
**Pull request by kochigami**
I followed http://doc.aldebaran.com/2-4/naoqi/audio/alsoundlocalization-api.html#alsoundlocalization-api
and this requires https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/21 for msg and srvs.

If there is any problem, please let me know.

services:
- /set_energy_computation
  ALSoundLocalizationProxy::setParameter 
  uses SetEnergyComputation.srv
- /set_sensitivity
  ALSoundLocalizationProxy::setParameter 
  uses SetSensitivity.srv
- /start_sound_localization
  ALSoundLocalizationProxy::subscribe
- /stop_sound_localization
  ALSoundLocalizationProxy::unsubscribe

topic: 
- /soundLocated
  ALSoundLocalization/SoundLocated()
  uses SoundLocated.msg

### CODE REVIEW

**Comment by Karsten1987** [comment]
:+1: 

a little remark: Could you please rename the files with underscore (`sound_localization.launch`, `naoqi_sound_localization.py`) rather than CamelCase? Just to be consistent with the other files in the package.

**Comment by kochigami** [comment]
Thank you very much for your comment.
I renamed them.

**Comment by kochigami** [comment]
- keep services, but used srv files are replaced from `naoqi_bridge_msgs` (https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/21) to `std_srvs` and `naoqi_bridge_msgs`  (https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/37)   
- This requires https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/37.

confirmed with
- [x] Pepper + ROS indigo
- [ ] Pepper + ROS kinetic
- [ ] NAO + ROS indigo
- [ ] NAO + ROS kinetic

**Comment by kochigami** [comment]
It seems that we can receive `soundLocated` topic without running `start_sound_localization` service.
In addition, without `set_energy_computation`service, it seems that we always receive the information about `energy`.
ref: 
http://doc.aldebaran.com/2-5/naoqi/audio/alsoundlocalization-api.html#alsoundlocalization-api
http://doc.aldebaran.com/2-1/naoqi/audio/alsounddetection-api.html#alsounddetection-api

I'm not sure when and how these services should be used now...

**Comment by kochigami** [comment]
This is a new feature, and I have some points I don't know a correct behavior for some API functions.
This may cause unexpected trouble when it is merged.
I close this and improve this in my local.
I'm sorry to leave this for a long time.

**Pull request closed without merging**
