### PR TITLE
[naoqi_apps] added two services and one topic related to external collision avoidance

### PR DESCRIPTION
**Pull request by kochigami**
I added two services for ```setOrthogonalSecurityDistance```and ```setTangentialSecurityDistance``` to extend pepper's move range, and one publisher for ```/move_failed``` event.
It requires two new services, which I will send another pull request for ```naoqi_bridge_msgs```.

I am still uncertain about the minimum distance which can be set to these two functions (I thought 0.001, but it might be wrong. I will modify it as soon as possible.).
In addition, I am not sure whether node name and program name are proper or not.

For everything, if there is any problem, please let me know. I am very sorry for troubling you.

### CODE REVIEW

**Comment by vrabaud** [comment]
That one is a new file so you have no excuse :) Please use a NaoqiNode. Thx

**Comment by k-okada** [comment]
> Please use a NaoqiNode. Thx

Do you mean naoqi_driver ?

--
◉ Kei Okada

**Comment by k-okada** [comment]
Oh, you mean NaoqiNode class of python API

--
◉ Kei Okada

**Comment by kochigami** [comment]
I'm very sorry for my late replying.
I used NaoqiNode, and added several services.

|Service name| Callback in Program|Related function in Naoqi|
:-----------------:|:---------------------------------:|:-------------------------:|
|/get_external_collision_protection_status|handleGetExternalCollisionProtectionEnabled | [getExternalCollisionProtectionEnabled](http://doc.aldebaran.com/2-1/naoqi/motion/reflexes-external-collision-api.html?highlight=setexternalcollision#ALMotionProxy::getExternalCollisionProtectionEnabled__ssCR)|
|/get_orthogonal_distance| handleGetOrthogonalSecurityDistanceSrv| [getOrthogonalSecurityDistance](http://doc.aldebaran.com/2-1/naoqi/motion/reflexes-external-collision-api.html?highlight=setexternalcollision#ALMotionProxy::getOrthogonalSecurityDistance)|
|/get_tangential_distance|handleGetTangentialSecurityDistanceSrv |[getTangentialSecurityDistance](http://doc.aldebaran.com/2-1/naoqi/motion/reflexes-external-collision-api.html?highlight=setexternalcollision#ALMotionProxy::getTangentialSecurityDistance) |
|/move_failed_information|handleMoveFailedInformationSrv | [getData("ALMotion/MoveFailed")](http://doc.aldebaran.com/2-1/naoqi/motion/reflexes-external-collision-api.html?highlight=movefailed#ALMotion/MoveFailed)|
|/set_external_collision_protection_status|handleSetExternalCollisionProtectionEnabled |[setExternalCollisionProtectionEnabled] (http://doc.aldebaran.com/2-1/naoqi/motion/reflexes-external-collision-api.html?highlight=setexternalcollision#ALMotionProxy::setExternalCollisionProtectionEnabled__ssCR.bCR)|
|/set_orthogonal_distance|handleSetOrthogonalSecurityDistanceSrv |[setOrthogonalSecurityDistance](http://doc.aldebaran.com/2-1/naoqi/motion/reflexes-external-collision-api.html?highlight=setexternalcollision#ALMotionProxy::setOrthogonalSecurityDistance) |
|/set_tangential_distance| handleSetTangentialSecurityDistanceSrv | [setTangentialSecurityDistance](http://doc.aldebaran.com/2-1/naoqi/motion/reflexes-external-collision-api.html?highlight=setexternalcollision#ALMotionProxy::setTangentialSecurityDistance__floatCR)|

**Comment by kochigami** [comment]
I modified ```/set_external_collision_protection_status``` service handler in accordance with https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/6 .
I added the output (True / False = succeeded / failed) of ```setExternalCollisionProtectionEnabled```.

If there is any problem, please let me know.

**Pull request closed without merging**
