### PR TITLE
[naoqi_pose] get current state of AutonomousLife

### PR DESCRIPTION
**Pull request by kochigami**
- adding service to get the current state of AutonomousLife
using this API:
http://doc.aldebaran.com/2-4/naoqi/interaction/autonomouslife-api.html#autonomouslife-api

This overrides https://github.com/ros-naoqi/naoqi_bridge/pull/53
This uses service file from std_srvs, on the other hand, #53 uses original service.

### CODE REVIEW

**Comment by furushchev** [comment]
@kochigami It looks really good feature! I think it'd be better if we can get this value not only by calling service but also via rostopic to read the state from multiple nodes. :+1:

**Comment by kochigami** [comment]
I confirmed 
`rostopic echo /(nao)_robot/pose/life/get_state`
`rosservice call /(nao)_robot/get_life_state`
with 
- [x] Pepper (NAOqi 2.5.5.5) + ROS indigo
- [x] Pepper (NAOqi 2.5.5.5) + ROS kinetic
- [x] NAO (NAOqi 2.1.4) + ROS indigo
- [x] NAO (NAOqi 2.1.4) + ROS kinetic

**Comment by nlyubova** [comment]
@kochigami  Thank you for testing!
@furushchev do you agree to merge?

**Comment by nlyubova** [comment]
@sambrose do you agree to merge?

**Comment by furushchev** [comment]
@nlyubova Confirmed that it works on real pepper robot. LGTM :+1: 
@kochigami Thanks a lot! :+1:

**Comment by nlyubova** [comment]
@furushchev I thought that @kochigami confirmed it on real robots. Sorry, I do not have an access to robots

**Comment by nlyubova** [comment]
@kochigami did you test on real Pepper and Nao, right?

**Comment by kochigami** [comment]
I confirmed with
>  Pepper (NAOqi 2.5.5.5) + ROS indigo
Pepper (NAOqi 2.5.5.5) + ROS kinetic
NAO (NAOqi 2.1.4) + ROS indigo
NAO (NAOqi 2.1.4) + ROS kinetic

However, I just tried 1. launch `nao(pepper)_bringup/nao(pepper)_full.launch` on one terminal and `rosservice call ...` and `rostopic echo ...` on another terminal with a real robot.
What should I do? I'm sorry for my misunderstanding.

**Comment by furushchev** [comment]
@nlyubova I mean I confirmed on real robot, thanks anyway. :+1:

**Comment by nlyubova** [comment]
@furushchev now I understood :)
@kochigami thank you for your work!

**Comment by nlyubova** [comment]
@furushchev thanks for you for testing !

**Pull request merged**
