### PR TITLE
fix for issue 31: to be tested

### LINKED ISSUE #31: [generate_urdf.py] Add dummy physical value to every physical link (Finger, Thumbs and gripper frames)
Gazebo plugin is not working anymore because the inertial tags disappeared during the last URDF generation. If a link has no physical value it cannot be simulated by Gazebo thus gazebo crashes without instanciating the controllers.
The values disappeared during this commit:
https://github.com/ros-naoqi/nao_robot/commit/535d34474d9f64ddb60f6f163656c10fcdf92774
Needs to be fixed in generate_urdf.py

### PR DESCRIPTION
**Pull request by keulYSMB**
added dummy intertial for gazebo simulation. resolve #31 : Needs testing on official Aldebaran URDFs

### CODE REVIEW

**Comment by vrabaud** [comment]
works for me. I updated the .urdf with https://github.com/ros-naoqi/nao_robot/commit/de011dbc0fa85d579466f27011158d729f511384

**Comment by vrabaud** [comment]
Gazebo .urdf still needs to be updated automatically though.

**Comment by keulYSMB** [comment]
Indeed, generating the link list is not necessarly an issue. More complicated would be to generate sensors plugins.
A while back we decided to wait for mimic joints to be handled by gazebo automatically before assessing this issue.
But code and library are ready to handle this I just didn't want to hardcode all the sensor values, hopping that we might get those value from Aldebaran's libs.

**Comment by vrabaud** [comment]
one day .... :) But thx for the patch. I saw my diff but I did not think inertia mattered. How foolish of me.

**Pull request merged**
