### PR TITLE
[naoqi_apps] add node and launch for ALMotion/ external-collision avoidance

### PR DESCRIPTION
**Pull request by kochigami**
This a new version of #48
I followed the Naoqi documenation (ALMotion, external-collision avoidance APIs) and this node has 

```
methods (services):
getChainClosestObstaclePosition
getExternalCollisionProtectionEnabled
getOrthogonalSecurityDistance
getTangentialSecurityDistance
setExternalCollisionProtectionEnabled
setOrthogonalSecurityDistance
setTangentialSecurityDistance
events (topics):
ALMotion/Safety/ChainVelocityClipped()
ALMotion/MoveFailed()
```

getChainClosestObstaclePosition (service) needs https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/12
getOrthogonalSecurityDistance, getTangentialSecurityDistance, setOrthogonalSecurityDistance and setTangentialSecurityDistance (service) need https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/10
ALMotion/Safety/ChainVelocityClipped() (event) needs https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/11

I wish someone kindly reviews this pull request.

topics

```
 rostopic echo /move_failed 
header: 
  seq: 1
  stamp: 
    secs: 1474083111
    nsecs: 859669923
  frame_id: ''
cause: Safety
status: 0
obstacle_position: 
  layout: 
    dim: []
    data_offset: 0
  data: [0.30000007152557373, 0.0, 0.0]

---
```

```
 rostopic echo /chain_velocity_clipped 
header: 
  seq: 1
  stamp: 
    secs: 1474082990
    nsecs: 122095108
  frame_id: ''
chain: LArm
obstacle_position: 
  x: -4.37113989449e-09
  y: -0.100000023842
  z: 0.0

---
```

services

```
rosservice call /get_chain_closes_obstacle_position "arm:
  data: 0
frame:
  data: 0" 
obstacle_position: 
  x: -0.389547646046
  y: 0.0328730270267
  z: -0.82798576355
```

```
rosservice call /get_external_collision_protection_status "name:
  data: 0" 
status: True
```

```
 rosservice call /get_orthogonal_distance 
orthogonal_distance: 0.40000000596
```

```
rosservice call /get_tangential_distance 
tangential_distance: 0.10000000149
```

```
rosservice call /set_external_collision_protection_status "name:
  data: 0
status: True" 
success: True
```

```
rosservice call /set_orthogonal_distance "orthogonal_distance: 0.0" 
success: False
rosservice call /set_orthogonal_distance "orthogonal_distance: 0.4" 
success: True

```

```
rosservice call /set_tangential_distance "tangential_distance: 0.0" 
success: False
rosservice call /set_tangential_distance "tangential_distance: 0.1" 
success: True
```

### CODE REVIEW

**Comment by k-okada** [comment]
I think this is ok to merge @ros-naoqi/developers

**Comment by mikaelarguedas** [comment]
this seems to depend on https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/11 and I guess several others.
I agree with https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/13#issuecomment-248440564 and all these PR should at least reference each other to be reviewed/merged all at once otherwise this code will fail when trying to import services

**Comment by Karsten1987** [comment]
lgtm 

minor remark. The `frame_id` inside the messages seem to be unset. Would it make sense to express the velocity in their related frame, such as `base_link` or the arm reference frame?

**Comment by kochigami** [comment]
@Karsten1987 
I'm sorry for my late response. Thank you very much for your comment. 
I'll update my pull-request tomorrow.

**Comment by kochigami** [comment]
I updated my pull-request to have ```frame_id``` to  topic ```/chain_velocity_clipped```.

However, I have two points I'm not sure from the Naoqi documentation :
1. how many chain name is available 
(I found ```LArm``` and ```RArm``` are published, but as for others, I'm not sure.)
2. which frame is referenced as ```LArm``` or ```RArm```
(I added Hand related frame, but I don't have confidence on it.)

Sorry for my unaccomplished work.

**Comment by kochigami** [comment]
Hi, 
> 1. how many chain name is available 

 I could find chain definition in http://doc.aldebaran.com/2-4/family/pepper_technical/bodyparts_pep.html

> 2. which frame is referenced as LArm or RArm

Sorry for my misunderstanding, all chains refer to ```FRAME_WORLD```.
I modified two topics as follows:
```
rostopic echo /chain_velocity_clipped 
header: 
  seq: 1
  stamp: 
    secs: 1475753979
    nsecs: 205518007
  frame_id: FRAME_WORLD
chain: 
  data: 2
obstacle_position: 
  x: -1.45519152284e-11
  y: 1.45519152284e-11
  z: 0.0
---
```
```
rostopic echo /move_failed 
header: 
  seq: 1
  stamp: 
    secs: 1475754020
    nsecs: 395179986
  frame_id: FRAME_WORLD
cause: Safety
status: 0
obstacle_position: 
  layout: 
    dim: []
    data_offset: 0
  data: [0.3000001013278961, 0.8999999761581421, 0.0]
---
```
If there is any problem, please let me know.

**Comment by suryaambrose** [comment]
Looks good to me, except for my remark in here : https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/19#issuecomment-258615592
which could cause a problem on [naoqi_apps/nodes/naoqi_externalCollisionAvoidance.py#208](https://github.com/ros-naoqi/naoqi_bridge/pull/60/files#diff-083fa805fd176c3d74dac308c0b60c7fR208) if running a Nao

**Comment by kochigami** [comment]
modified:
update in accordance with https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/19

confirmed with:
- [x] Pepper (Naoqi 2.5.5.5) + ros indigo
- [ ] NAO (NAOqi 2.4.3) + ros indigo
- [ ] Pepper (Naoqi 2.5.5.5) + ros kinetic
- [ ] NAO (NAOqi 2.4.3) + ros kinetic

**Comment by kochigami** [comment]
When I tried this pull request with NAO (both kinetic and indigo), there is something wrong.

- `getExternalCollisionProtectionEnabled` & `setExternalCollisionProtectionEnabled` 

A setting function succeeds to change a status, but when getting a status, it does not change.
On the other hand, when I used Pepper, it works correctly. In addition, it seems that no owner consent is required.
ref:
http://doc.aldebaran.com/2-4/naoqi/motion/reflexes-external-collision-api.html#ALMotion
=> `setExternalCollisionProtectionEnabled`


- `move_failed` topic

I couldn't get `ALMove/MoveFailed` key value for NAO.


In addition, I haven't learned the correct behavior of  `ALMotion/Safety/ChainVelocityClipped()` yet (both NAO and Pepper).
- `clipped_velocity` topic

I will leave this as it is for now. I will look into my codes again.
Then, I will create `pepper_apps` or something like that and separate services which work correctly only for Pepper.

**Comment by kochigami** [comment]
This is a new feature, and I have some points I don't know a correct behavior for some API functions. 
This may cause unexpected trouble when it is merged.
I close this and improve this in my local.
I'm sorry to leave this for a long time.

**Pull request closed without merging**
