### PR TITLE
Create naoqi_navigation

### PR DESCRIPTION
**Pull request by lsouchet**
Add naoqi_navigation folder containing nodes for Pepper charging station display and Pepper localization display.

* Charging station:
- naoqi_rviz_plugins lib provides visualization tools inside rviz of Pepper charging station
- naoqi_navigation contains a node to publish ROS nodes from NAOqi informations

* Localization:
Starting from 2.5.2, Pepper can localize in his environment. Some nodes to display:
- Explorated map
- Robot localization

### CODE REVIEW

**Comment by Karsten1987** [comment]
lgtm.

Does this launch file stay separated from any other launch file and should this be launched somehow by default from `pepper_bringup` ?

**Comment by lsouchet** [comment]
Hi Karsten,
As it is a pretty new feature, available on NAOqi2.5.2+ only, I would keep it separated from other launch files and make it available for users to launch it.

**Comment by mikaelarguedas** [comment]
Note that naoqi2.5/libqi2.5 is available only on ros kinetic (not Jade and
indigo if I remember well) so we may want to branch out at that point.

As a side notes the KneePitch mesh should already be available in the
pepper_meshes package and were not officially "publicly releasable without
licence" according to Aldebaran. Maybe the legal position changed in that
since.
Otherwise LGTM

**Comment by lsouchet** [comment]
You are right about the meshes, they are not mandatory here, I'll just remove them from the PR and check  again internally.

As for the 2.5 compatibility, I don't know how it is versionned on your side. I tested it on indigo locally with a NAOqi 2.5 and it works, probably because I only use old libqi calls. So I am not sure branching is mandatory here.

**Comment by Karsten1987** [comment]
@lsouchet Is there a way to check for the libqi version at the beginning of your script? Would make sense to print an error message in case they use the wrong version. What do you think?

**Comment by mikaelarguedas** [comment]
@lsouchet Regarding the meshes, we can add the pod mesh to `pepper_meshes` with all the other ones and this way it can be displayed in rviz with your plugin. That package explicitly ask the user to accept the licence agreement before installing the meshes so we should be good.

**Comment by lsouchet** [comment]
@Karsten1987 It doesn't really rely on libqi version, but more on NAOqi version, it don't think there is an easy way of knowing that. Perhaps I could differentiate the exception between a "such method does not exist because your NAOqi version is too old" and "I am not currently localized, hence I cannot publish anything". Don't know if it is easy either though. What do you think?

@mikaelarguedas I'll check with my hierarchy, I'll probably submit it in a later PR. Thanks anyway.

**Comment by lsouchet** [comment]
any update? Would you consider merging it?
Thanks!

**Comment by vrabaud** [comment]
@lsouchet , maybe you want to announce it on the SIG. Maybe it is related to: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ros-sig-aldebaran/4Cl1cckzao0/iAC7-SY3AgAJ
Also, is 2.5.2 released ? I think there was a way to check for NAOqi's version, something like naoqi.__version__ but not as clean. Also, you could try an import of what you need and show a warning message for any error.

**Comment by lsouchet** [comment]
@vrabaud I'll look for a way of handling the naoqi version.
I was planning on announcing it once the 2.5.2 was officially released.

**Comment by suryaambrose** [comment]
@mikaelarguedas libqi2.5 is indeed only available on kinetic, but is actually not necessary here. Different versions of libqi are totally able to communicate (meaning libqi2.3 on your desktop and libqi 2.5 on the robot can understand each other, and the other way around too). 
Checking the naoqi version makes sense, but as long as the robot is on the correct version, this code should work for every ROS distro.

**Comment by vrabaud** [comment]
2.5 seems out http://doc.aldebaran.com/2-5/news/index.html , maybe an announcement would be nice now ?

**Pull request merged**
