### PR TITLE
[naoqi_apps] add node and launch for ALListeningMovement

### PR DESCRIPTION
**Pull request by kochigami**
This is for http://doc.aldebaran.com/2-4/naoqi/interaction/autonomousabilities/allisteningmovement-api.html#allisteningmovement-api.

memo: 
- It needs SetEnabled.srv in https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/30
- IsActive.srv is in ALTracker related pull-request, (https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/27)
and I'm thinking that I have to rename it for general use. 
- It is something wrong with isRunning method.
```
rosservice call /listening_movement_is_running
[ERROR] [WallTime: 1478745757.759069] Error processing request: proxy_isRunning() takes exactly 2 arguments (1 given)
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/kochigami/catkin_ws/src/naoqi_bridge/naoqi_apps/nodes/naoqi_listening_movement.py", line 66, in handleIsRunningSrv\n    res.status = self.listeningMovementProxy.isRunning()\n', '  File "/home/kochigami/naoqi/pynaoqi-python2.7-2.1.0.19-linux64/inaoqi.py", line 326, in isRunning\n    def isRunning(self, *args): return _inaoqi.proxy_isRunning(self, *args)\n', 'TypeError: proxy_isRunning() takes exactly 2 arguments (1 given)\n']
```

### CODE REVIEW

**Comment by kochigami** [comment]
- SetEnabled.srv in ros-naoqi/naoqi_bridge_msgs#30
replaced by ```std_srvs/SetBool``` based on the advice in https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/30

- IsActive.srv
replaced by ```std_srvs/Trigger```

- isRunning
I deleted it.

**Comment by kochigami** [comment]
- delete `self.run()` because it is not used

confirmed with:
- [x] Pepper + ros indigo
- [ ] Pepper + ros kinetic
- [ ] NAO + ros indigo
- [ ] NAO + ros kinetic

**Comment by kochigami** [comment]
When I use NAO, this doesn't work.
That is because the latest NAOqi version for NAO is 2.1.4, which doesn't have a proxy to `ALListeningMovement`.

I added lines for checking NAOqi version and robot type, but this is work in progress.

**Comment by nlyubova** [comment]
Thank you!

**Pull request merged**
