### PR TITLE
cleanup, approching pep8 pep257 compliance

### PR DESCRIPTION
**Pull request by mikaelarguedas**
long due cleanup/linting

### CODE REVIEW

**Comment by nlyubova** [comment]
@mikaelarguedas should we merge it?

**Comment by mikaelarguedas** [comment]
I would like to actually test it on the new URDFs to see if anything broke along the way. Would you mind sending me (via PM) the latest URDFs for all robots? I will use them to validate any change on the generator

**Comment by mikaelarguedas** [comment]
Tested on the latest set of URDF files (thanks @nlyubova). Fixed typo accordingly and validated that the generated files are identical.
Waiting for review and can be squashed and merges

**Comment by nlyubova** [comment]
Nice re-formatting ! did you actually change some values ? :) should we re-generate URDF with this new version?

**Comment by mikaelarguedas** [comment]
Nope didn't change any value just refactored and cleanup the code. I compared the generated urdfs using  http://prettydiff.com/ amd the generated are exactly identical.
Once this is merged I'll add the changes we talked about a few months ago (adding dummy inertias automatically when needed etc)

**Comment by nlyubova** [comment]
+1

**Pull request merged**
