### PR TITLE
[naoqi_apps] add node and launch for ALFaceDetection

### PR DESCRIPTION
**Pull request by kochigami**
I followed http://doc.aldebaran.com/2-4/naoqi/peopleperception/alfacedetection-api.html#alfacedetection-api
and this needs https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/28 for msgs and srvs.
I didn't make the service for ```bool ALFaceDetectionProxy::importOldDatabase(const std::string& policy)``` because I think it is used only once and we don't have to use it on ROS.

If there is any problem, please let me know.
- - - - - - -
topic: ```/face_detected```
``` FaceDetected() ```
I created msg files based on http://doc.aldebaran.com/2-4/naoqi/peopleperception/alfacedetection.html#alfacedetection
msg/FaceDetected.msg has
- msg/FaceInfo.msg
- msg/TimeFilteredRecoInfo.msg

msg/FaceInfo.msg
= msg/FaceDetectionExtraInfo.msg + msg/FaceDetectionShapeInfo.msg

msg/FaceDetectionExtraInfo.msg has 
- msg/EyePoints.msg
- msg/MouthPoints.msg 
- msg/NosePoints.msg 

```

---
header: 
  seq: 335
  stamp: 
    secs: 1477994512
    nsecs: 522608041
  frame_id: ''
face_info: 
  shape_info: 
    alpha: -0.0155988810584
    beta: 0.0483238063753
    size_x: 0.243342548609
    size_y: 0.251283794641
  extra_info: 
    face_id: 1
    recognition_score: 0.0
    face_label: ''
    left_eye: 
      eye_center_x: 0.499164193869
      eye_center_y: -0.386590451002
      nose_side_limit_x: 0.499164193869
      nose_side_limit_y: -0.386590451002
      ear_side_limit_x: 0.499164193869
      ear_side_limit_y: -0.386590451002
    right_eye: 
      eye_center_x: 0.499164193869
      eye_center_y: -0.386590451002
      nose_side_limit_x: 0.499164193869
      nose_side_limit_y: -0.386590451002
      ear_side_limit_x: 0.499164193869
      ear_side_limit_y: -0.386590451002
    nose: 
      bottom_center_limit_x: 0.499164193869
      bottom_center_limit_y: -0.386590451002
      bottom_left_limit_x: 0.499164193869
      bottom_left_limit_y: -0.386590451002
      bottom_right_limit_x: 0.499164193869
      bottom_right_limit_y: -0.386590451002
    mouth: 
      left_limit_x: 0.499164193869
      left_limit_y: -0.386590451002
      right_limit_x: 0.499164193869
      right_limit_y: -0.386590451002
      top_limit_x: 0.499164193869
      top_limit_y: -0.386590451002
time_filtered_reco_info: 
  status: 0
  face_label: []
camera_pose_in_torso_frame: 
  linear: 
    x: 0.042243603617
    y: 0.0330938622355
    z: 0.333000004292
  angular: 
    x: 0.0
    y: -0.0
    z: 0.391165047884
camera_pose_in_robot_frame: 
  linear: 
    x: 0.0721535384655
    y: 0.0309213902801
    z: 1.14981913567
  angular: 
    x: 0.025911744684
    y: 0.0507121346891
    z: 0.391691565514
camera_id: 0
```

services:

```/clear_database ```:  
```bool ALFaceDetectionProxy::clearDatabase()```
srv/ClearDatabase.srv

```/forget_person ```: 
```bool ALFaceDetectionProxy::forgetPerson(const std::string& name)```
 srv/ForgetPerson.srv 

```/get_learned_facesList ```:
``` AL::ALValue ALFaceDetectionProxy::getLearnedFacesList() ```
srv/GetLearnedFacesList.srv

``` /get_recognition_confidence_threshold ```: 
``` float ALFaceDetectionProxy::getRecognitionConfidenceThreshold()  ```
 srv/GetRecognitionConfidenceThreshold.srv 

``` /is_recognition_enabled ``` : 
``` bool ALFaceDetectionProxy::isRecognitionEnabled() ```
 srv/IsRecognitionEnabled.srv

``` /is_tracking_enabled ```:
``` bool ALFaceDetectionProxy::isTrackingEnabled()  ```

``` /learn_face ```: 
``` bool ALFaceDetectionProxy::learnFace(const std::string& name)  ```
srv/LearnFace.srv

``` /relearn_face ```:
``` bool ALFaceDetectionProxy::reLearnFace(const std::string& name)  ```
 srv/ReLearnFace.srv 

``` /set_recognition_confidence_threshold ```:
``` void ALFaceDetectionProxy::setRecognitionConfidenceThreshold(float threshold) ```
 srv/SetRecognitionConfidenceThreshold.srv 

``` /set_recognition_enabled ```: 
```  void ALFaceDetectionProxy::setRecognitionEnabled(const bool& enable)  ```
 srv/SetRecognitionEnabled.srv 

``` /set_tracking_enabled ```:
``` void ALFaceDetectionProxy::setTrackingEnabled(const bool& enable)  ```
 srv/SetTrackingEnabled.srv

### CODE REVIEW

**Comment by Karsten1987** [comment]
what is the difference to https://github.com/ros-naoqi/naoqi_bridge/pull/65 ?

**Comment by kochigami** [comment]
Thank you very much for your comment and sorry for my late response.

The main difference of ALPeoplePerception (#65) and ALFaceDetection (this pull request) is that
the former is used to recognize people by adding labels, 
on the other hand, the latter is used to learn / recognize people's name, I think.  

I also added topic and services explanation of my pull request can handle in the first my comment.

**Comment by nlyubova** [comment]
+1 should we merge it one day ? what do you think @suryaambrose

**Comment by kochigami** [comment]
This is an old pull-request.
This may cause unexpected trouble when it is merged.
I close this and improve this in my local.
I'm sorry to leave this for a long time.

**Pull request closed without merging**
