### PR TITLE
[naoqi_apps] add node and launch for ALMotion/ locomotion control

### PR DESCRIPTION
**Pull request by kochigami**
I followed the Naoqi documenation (ALMotion, locomotion control APIs) and this node deals with

```
methods (services):
getMoveArmsEnabled
getNextRobotPosition
getRobotPosition
getRobotVelocity
moveInit
moveIsActive
setMoveArmsEnabled
stopMove
waitUntilMoveIsFinished
```

I didn't make 
`move`, `moveTo`, (we can call them by naoqi_driver.launch) `moveToward`, `getMoveConfig` 
`setFootSteps`, `setFootStepsWithSpeed`, `getFootSteps` (These are available only for NAO)

getMoveArmsEnabled needs https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/15 and https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/14
getNextRobotPosition needs https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/18
getRobotPosition needs https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/17
getRobotVelocity needs https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/16
moveIsActive needs https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/13

```
 rosservice call /get_move_arms_enabled "arm:
  data: 1" 
success: True
```

```
 rosservice call /get_next_robot_position 
pose: 
  x: 0.0
  y: 0.0
  theta: 0.0
```

```
 rosservice call /get_robot_position "use_sensors_values: false" 
pose: 
  x: 0.141362503171
  y: 0.161213904619
  theta: 0.633683264256

```

```
rosservice call /get_robot_velocity 
velocity: 
  x: 0.0
  y: 0.0
  theta: 0.0
```

```
rosservice call /set_move_arms_enabled "left_arm: false
right_arm: false" 
```

```
rosservice call /move_init 

rosservice call /move_is_active 
status: False

rosservice call /stop_move

rosservice call /wait_until_move_is_finished 
```

### CODE REVIEW

**Comment by kochigami** [comment]
I also added ```getMoveConfig``` service.
However, I only tested on Pepper, I'm not sure yet what happens when I tried it on Nao.

```
rosservice call /get_move_config "move_config_name:
  data: 0" 
move_config: 
  max_vel_xy: 0.550000011921
  max_vel_theta: 2.0
  max_acc_xy: 0.550000011921
  max_acc_theta: 3.0
  max_jerk_xy: 5.0
  max_jerk_theta: 50.0
  torso_wy: 0.174532920122

 rosservice call /get_move_config "move_config_name:
  data: 1" 
move_config: 
  max_vel_xy: 0.10000000149
  max_vel_theta: 0.20000000298
  max_acc_xy: 0.10000000149
  max_acc_theta: 0.10000000149
  max_jerk_xy: 0.20000000298
  max_jerk_theta: 0.20000000298
  torso_wy: -0.174532920122

 rosservice call /get_move_config "move_config_name:
  data: 2" 
move_config: 
  max_vel_xy: 0.34999999404
  max_vel_theta: 1.0
  max_acc_xy: 0.300000011921
  max_acc_theta: 0.75
  max_jerk_xy: 1.0
  max_jerk_theta: 2.0
  torso_wy: 0.0
```

**Comment by Karsten1987** [comment]
@suryaambrose can you verify this?

**Comment by suryaambrose** [comment]
See my comment here : https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/20#issuecomment-258619746

**Comment by kochigami** [comment]
This is an old pull-request.
This may cause unexpected trouble when it is merged.
I close this and improve this in my local.
I'm sorry to leave this for a long time.

**Pull request closed without merging**
