### PR TITLE
[naoqi_apps] Add naoqi tactile py and launch

### PR DESCRIPTION
**Pull request by kochigami**
I added `naoqi_tactile` related code for Pepper. This program is almost same as `nao_tactile.py`, and `tactile.launch` in `nao_apps` directory, but I added back bumper feature and hand touch detection. 
The node name is `/naoqi_tactile`.
It publishes  `/tactile_touch`, `/bumper` and `/hand_touch`.

This change requires other pull-requests about HandTouch.msg, Bumper.msg in `naoqi_bridge_msgs`. ([ add back bumper value for Pepper #3 ](https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/3), [ add HandTouch.msg for hand touch detection #4 ](https://github.com/ros-naoqi/naoqi_bridge_msgs/pull/4)) 

I tried it on Naoqi 2.3 version Pepper, linux 14.04, and ROS indigo.
If there is any problem, please let me know.

### CODE REVIEW

**Comment by vrabaud** [comment]
ok, I guess we can delete nao_tactile.py then ? Did you remove any functionality ?
So all that looks good but it is the old style to make a module. We created an abstraction (NaoqiNode) that makes things easier to code (like ip parameters and shutdown).
Can you please try to see if you can get that working ? A good example is here: https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_driver_py/nodes/naoqi_joint_states.py#L50
In the end, a lot of code will be removed: the command line arguments, the creation of self.broker, no call to ALModule.__init_ but to NaoqiNode,__init__, and the memProxy should be created with https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_driver_py/src/naoqi_driver/naoqi_node.py#L128
Thx

**Comment by vrabaud** [comment]
Any way you can take the comments into account ? Thx.

**Comment by vrabaud** [comment]
@kochigami , please take the comments into account.

**Comment by kochigami** [comment]
I am very sorry for my late replying.
I used ```getData``` instead of ```subscribeToEvent``` because I don't know how to use a callback function in NaoqiNode, which inherits from Thread class.

I tried my program with
Nao (version 2.1.4.13) and
Pepper (version 2.4.2.26).

My concern is this warning message
```
[WARN] [WallTime: 1454825044.174728] Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
```
after I launched ```tactile.launch``` and touched sensors (ex. bumper) of a robot many times in a fast speed.
When I ran ```rostopic echo /bumper (/hand_touch, /tactile_touch)```, I failed to subscribe some data.

I am very sorry for my trouble again.

**Comment by kochigami** [comment]
I will close this because `naoqi_driver` package publishes topic related to `ALTouch`.
I am very sorry to have left this pull-request for a long time.

**Pull request closed without merging**
